---
- name: common configuration for all systems
  hosts: all
  remote_user: root
  become: true

  roles:
    - geerlingguy.git
    - geerlingguy.nodejs
    - geerlingguy.mysql
    - futurice.pip

  tasks:
    - name: python deps
      pip:
        name: pexpect

    - name: expect dep
      apt:
        name: expect

    - name: install node packages for bot
      npm:
        path: /vagrant

    - name: clone headless wallet
      git:
        repo: "https://github.com/byteball/headless-byteball.git"
        dest: /home/vagrant/headless-byteball

    - name: install headless wallet dependencies
      npm:
        path: /home/vagrant/headless-byteball

    - name: start wallet background task
      command: expect /vagrant/headless-wallet-start.exp
